before_install:
  - 'sudo apt-get update'
compiler: clang
install:
  - 'sudo apt-get install clang'
  - 'export CXX="clang-6"'
  - 'wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -'
  - 'sudo apt-get update'
  - 'sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0
    \ main"'
  - 'sudo apt-get install -y clang-6.0 lld-6.0'
language: cpp
script: 'bash -c ./build.sh'
